[project]
name = "iovance-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "anthropic>=1.11.0",
    "en-core-web-sm",
    "mcp<2",
    "ollama>=0.6.3",
    "opensearch-py>=3.2.0",
    "presidio-analyzer>=2.2.364",
    "presidio-anonymizer>=2.2.364",
    "pypdf>=6.19.0",
    "pyyaml>=6.0.3",
    "sentence-transformers>=6.1.0",
    "streamlit>=1.65.0",
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
